[package]
edition = "2021"
name = "node-altjtalk-binding"
version = "0.2.1"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.12.2", default-features = false, features = ["napi4"] }
napi-derive = "2.12.2"

jpreprocess = "0.8.1"
jbonsai = { git = "https://github.com/jpreprocess/jbonsai.git", rev = "f5536f6d0fd2259c1bf0bfdfb7fcdb410c68baf3" }
audiopus = "=0.3.0-rc.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
